//
// Created by Oleg Elifantiev on 28.02.2021.
//

#ifndef SMART_WIPERS_CONFIG_H
#define SMART_WIPERS_CONFIG_H

#define VERSION "v0.2"
#define ENABLE_PARKING
#define xDEBUG_REPORT_VEHICLE_STATE
#define xDEBUG_REPORT_MOTION
#define xDEBUG_REPORT_STEERING_SWITCHES

#define MAX_OUT_TEMP 2.0

#endif //SMART_WIPERS_CONFIG_H
